[workspace]
members = ["asusctl", "asus-notify", "daemon", "daemon-user", "rog-platform", "rog-dbus", "rog-anime", "rog-aura", "rog-profiles", "rog-control-center"]

[workspace.package]
version = "4.5.0-rc3"

[workspace.dependencies]
async-trait = "^0.1"
tokio = { version = "^1.21.1", features = ["macros", "rt-multi-thread", "time"]}
concat-idents = "1.1.3"
dirs = "^4.0"
smol = "^1.2"

zbus = "^3.1.0"
zbus_macros = "^2.0"
zvariant = "^3.2"
zvariant_derive = "^3.2"
logind-zbus = { version = "^3.0" } #, default-features = false, features = ["non_blocking"] }

serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
toml = "^0.5.8"

log = "^0.4"
env_logger = "^0.9"

glam = { version = "^0.21.2", features = ["serde"] }
gumdrop = "^0.8"
udev = "^0.6"
rusb = "^0.9"
sysfs-class = "^0.1.2"
inotify = "^0.10.0"

png_pong = "^0.8.0"
pix = "0.13"
tinybmp = "^0.3.3"
gif = "^0.11.2"

notify-rust = { version = "^4.3", default-features = false, features = ["z"] }

[profile.release]
# thin = 57s, asusd = 9.0M
# fat = 72s, asusd = 6.4M
lto = "fat"
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = false
opt-level = 1

[profile.bench]
debug = false
opt-level = 3
