[package]
name = "rog-control-center"
license = "MPL-2.0"
version.workspace = true
authors = ["Luke D. Jones <luke@ljones.dev>"]
edition = "2021"

[features]
#default = ["mocking"]
#mocking = []

[dependencies]

libappindicator = "0.9" # Tray icon
gtk = "0.18"

asusd = { path = "../asusd" }
rog_anime = { path = "../rog-anime" }
rog_dbus = { path = "../rog-dbus" }
rog_aura = { path = "../rog-aura" }
rog_profiles = { path = "../rog-profiles" }
rog_platform = { path = "../rog-platform" }
supergfxctl = { git = "https://gitlab.com/asus-linux/supergfxctl.git", default-features = false }

gumdrop.workspace = true
log.workspace = true
env_logger.workspace = true

tokio.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
zbus.workspace = true
dirs.workspace = true
notify-rust.workspace = true

png_pong.workspace = true

versions.workspace = true

nix = "^0.26.1"
tempfile = "3.3.0"

i-slint-backend-selector = { git = "https://github.com/flukejones/sixtyfps.git" }
i-slint-core = { git = "https://github.com/flukejones/sixtyfps.git" }
i-slint-backend-winit = { git = "https://github.com/flukejones/sixtyfps.git" }
winit = "*"

[dependencies.slint]
git = "https://github.com/flukejones/sixtyfps.git"
default-features = false
features = ["std", "compat-1-0", "backend-winit-wayland", "backend-linuxkms", "renderer-femtovg"]

[build-dependencies.slint-build]
git = "https://github.com/flukejones/sixtyfps.git"

[dev-dependencies]
cargo-husky.workspace = true