[package]
name = "rog-control-center"
license = "MPL-2.0"
version.workspace = true
authors = ["Luke D. Jones <luke@ljones.dev>"]
edition = "2021"

[features]
#default = ["mocking"]
#mocking = []

[dependencies]
egui = "0.24.1"
eframe = "0.24.1"
egui_plot = "0.24.1"
# egui = { path = "../../egui/crates/egui" }
# eframe = { path = "../../egui/crates/eframe" }

libappindicator = "0.8" # Tray icon
gtk = "0.16"

asusd = { path = "../asusd" }
rog_anime = { path = "../rog-anime" }
rog_dbus = { path = "../rog-dbus" }
rog_aura = { path = "../rog-aura" }
rog_profiles = { path = "../rog-profiles" }
rog_platform = { path = "../rog-platform" }
supergfxctl = { git = "https://gitlab.com/asus-linux/supergfxctl.git", default-features = false }

gumdrop.workspace = true
log.workspace = true
env_logger.workspace = true

tokio.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
zbus.workspace = true
dirs.workspace = true
notify-rust.workspace = true

png_pong.workspace = true

versions.workspace = true

nix = "^0.26.1"
tempfile = "3.3.0"

# [patch.crates-io]
# egui = { git = "https://github.com/flukejones/egui" }
# eframe = { git = "https://github.com/flukejones/egui" }

[dev-dependencies]
cargo-husky.workspace = true