[package]
name = "rog_profiles"
version.workspace = true
authors = ["Luke D. Jones <luke@ljones.dev>"]
edition = "2021"

[features]
default = ["dbus"]
dbus = ["zvariant", "zvariant_derive"]

[dependencies]
udev.workspace = true
serde.workspace = true
serde_derive.workspace = true

zvariant = { workspace = true, optional = true }
zvariant_derive = { workspace = true, optional = true }