[package]
name = "rog_platform"
version.workspace = true
edition = "2021"

[dependencies]
log.workspace = true
rog_aura = { path = "../rog-aura" }
serde.workspace = true
serde_derive.workspace = true
zvariant.workspace = true
zvariant_derive.workspace = true
sysfs-class.workspace = true
concat-idents.workspace = true
udev.workspace = true
inotify.workspace = true

rusb.workspace = true